// <auto-generated />
using System;
using Infraestructure_Layer.InMemoryDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure_Layer.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250124191827_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Infraestructure_Layer.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fb65126-a34f-4834-b5ea-b84e8ebc5b99"),
                            Age = 35,
                            LastName = "Lorenzo Leon",
                            Name = "Juan Miguel"
                        },
                        new
                        {
                            Id = new Guid("a25b788d-2396-4927-870e-bbe5cd70b1da"),
                            Age = 36,
                            LastName = "Gonzalez Gutierrez",
                            Name = "Pedro Luis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
